In [1]:
import numpy as np
import pandas as pd

In [2]:
df1=pd.read_csv("matches.csv")

In [4]:
df2=pd.read_csv("deliveries.csv")

In [5]:
#35.Find the bowler with the best economy rate in each season.
df1.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [6]:
df2.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [11]:
data1=df1[["id","season"]]
data2=df2[["match_id","bowler","over","total_runs"]]

In [12]:
res=pd.merge(data1,data2,left_on="id",right_on="match_id",how="inner")

In [13]:
res

             id   season  match_id         bowler  over  total_runs
0        335982  2007/08    335982        P Kumar     0           1
1        335982  2007/08    335982        P Kumar     0           0
2        335982  2007/08    335982        P Kumar     0           1
3        335982  2007/08    335982        P Kumar     0           0
4        335982  2007/08    335982        P Kumar     0           0
...         ...      ...       ...            ...   ...         ...
260915  1426312     2024   1426312     AK Markram     9           1
260916  1426312     2024   1426312     AK Markram     9           1
260917  1426312     2024   1426312  Shahbaz Ahmed    10           1
260918  1426312     2024   1426312  Shahbaz Ahmed    10           1
260919  1426312     2024   1426312  Shahbaz Ahmed    10           1

[260920 rows x 6 columns]

In [24]:
res.groupby(["season","bowler"])["total_runs"].sum()

season   bowler
2007/08  A Kumble             314
         A Mishra             140
         A Nehra              357
         A Nel                 31
         A Symonds            106
                             ...
2024     Washington Sundar     73
         YS Chahal            548
         Yash Dayal           472
         Yash Thakur          405
         Yudhvir Singh         52
Name: total_runs, Length: 1948, dtype: int64

In [25]:
res.groupby(["season","bowler"])["over"].count()

season   bowler
2007/08  A Kumble             236
         A Mishra             123
         A Nehra              280
         A Nel                 18
         A Symonds             44
                             ...
2024     Washington Sundar     30
         YS Chahal            362
         Yash Dayal           322
         Yash Thakur          225
         Yudhvir Singh         24
Name: over, Length: 1948, dtype: int64

In [30]:
res

             id   season  match_id         bowler  over  total_runs
0        335982  2007/08    335982        P Kumar     0           1
1        335982  2007/08    335982        P Kumar     0           0
2        335982  2007/08    335982        P Kumar     0           1
3        335982  2007/08    335982        P Kumar     0           0
4        335982  2007/08    335982        P Kumar     0           0
...         ...      ...       ...            ...   ...         ...
260915  1426312     2024   1426312     AK Markram     9           1
260916  1426312     2024   1426312     AK Markram     9           1
260917  1426312     2024   1426312  Shahbaz Ahmed    10           1
260918  1426312     2024   1426312  Shahbaz Ahmed    10           1
260919  1426312     2024   1426312  Shahbaz Ahmed    10           1

[260920 rows x 6 columns]

In [33]:
data1=df1[["id","season"]]
data2=df2[["match_id","bowler","over","total_runs"]] 
res=pd.merge(data1,data2,left_on="id",right_on="match_id",how="inner") 
bowler=res.groupby(["season","bowler"])["total_runs"].sum().reset_index(name="sum") 
balls_count = res.groupby(["season", "bowler"])["over"].count().reset_index(name="balls_bowled")                                                                                
balls_count["overs_bowled"] = balls_count["balls_bowled"] / 6 
bowler_stats=pd.merge(bowler,balls_count,on=["season","bowler"]) 
bowler_stats["economy"]=bowler_stats["sum"]/bowler_stats["overs_bowled"]

In [34]:
bowler_stats

       season             bowler  sum  balls_bowled  overs_bowled    economy
0     2007/08           A Kumble  314           236     39.333333   7.983051
1     2007/08           A Mishra  140           123     20.500000   6.829268
2     2007/08            A Nehra  357           280     46.666667   7.650000
3     2007/08              A Nel   31            18      3.000000  10.333333
4     2007/08          A Symonds  106            44      7.333333  14.454545
...       ...                ...  ...           ...           ...        ...
1943     2024  Washington Sundar   73            30      5.000000  14.600000
1944     2024          YS Chahal  548           362     60.333333   9.082873
1945     2024         Yash Dayal  472           322     53.666667   8.795031
1946     2024        Yash Thakur  405           225     37.500000  10.800000
1947     2024      Yudhvir Singh   52            24      4.000000  13.000000

[1948 rows x 6 columns]

In [35]:
res.groupby(["season","bowler"])["total_runs"].sum()/pd.Series(["over"]).count()

season   bowler
2007/08  A Kumble             314.0
         A Mishra             140.0
         A Nehra              357.0
         A Nel                 31.0
         A Symonds            106.0
                              ...
2024     Washington Sundar     73.0
         YS Chahal            548.0
         Yash Dayal           472.0
         Yash Thakur          405.0
         Yudhvir Singh         52.0
Name: total_runs, Length: 1948, dtype: float64

In [36]:
#36.Compute total number of 6s hit by each team per season.
df1.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [37]:
df2.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [38]:
df2["batsman_runs"].unique()

array([0, 4, 6, 1, 2, 5, 3])

In [39]:
data1=df1[["id","season"]]
data2=df2[["match_id","batting_team","batsman_runs"]]

In [40]:
result=pd.merge(data1,data2,left_on="id",right_on="match_id",how="inner")

In [41]:
result=result[result["batsman_runs"]==6]

In [42]:
result

             id   season  match_id           batting_team  batsman_runs
10       335982  2007/08    335982  Kolkata Knight Riders             6
20       335982  2007/08    335982  Kolkata Knight Riders             6
25       335982  2007/08    335982  Kolkata Knight Riders             6
60       335982  2007/08    335982  Kolkata Knight Riders             6
65       335982  2007/08    335982  Kolkata Knight Riders             6
...         ...      ...       ...                    ...           ...
260868  1426312     2024   1426312  Kolkata Knight Riders             6
260869  1426312     2024   1426312  Kolkata Knight Riders             6
260889  1426312     2024   1426312  Kolkata Knight Riders             6
260895  1426312     2024   1426312  Kolkata Knight Riders             6
260908  1426312     2024   1426312  Kolkata Knight Riders             6

[13051 rows x 5 columns]

In [43]:
result.groupby(["season","batting_team"])["batsman_runs"].count()

season   batting_team
2007/08  Chennai Super Kings             86
         Deccan Chargers                 92
         Delhi Daredevils                54
         Kings XI Punjab                 95
         Kolkata Knight Riders           76
                                       ...
2024     Mumbai Indians                 133
         Punjab Kings                   120
         Rajasthan Royals               112
         Royal Challengers Bengaluru    165
         Sunrisers Hyderabad            178
Name: batsman_runs, Length: 146, dtype: int64

In [44]:
#37.Find the number of matches won by each team per venue.
data1=df1[["id","venue","winner"]]
data2=df2[["match_id","batting_team"]]

In [45]:
res=pd.merge(data1,data2,left_on="id",right_on="match_id",how="inner")

In [47]:
res.groupby(["venue","batting_team"])["winner"].count()

venue                             batting_team
Arun Jaitley Stadium              Chennai Super Kings            241
                                  Delhi Capitals                 843
                                  Delhi Daredevils               857
                                  Kings XI Punjab                246
                                  Kolkata Knight Riders          253
                                                                ...
Zayed Cricket Stadium, Abu Dhabi  Mumbai Indians                 369
                                  Punjab Kings                   123
                                  Rajasthan Royals               236
                                  Royal Challengers Bangalore    240
                                  Sunrisers Hyderabad            248
Name: winner, Length: 506, dtype: int64

In [48]:
#38.Calculate strike rate of each batsman (runs per ball faced).

In [ ]:
#39.Count how many deliveries were bowled by each bowler in powerplay overs.