In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("Bengaluru_House_Data.csv")

In [3]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [4]:
df["size"].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [5]:
df["size"]=df["size"].str.replace(" BHK","")

In [6]:
df["size"].unique()

array(['2', '4 Bedroom', '3', '4', '6 Bedroom', '3 Bedroom', '1', '1 RK',
       '1 Bedroom', '8 Bedroom', '2 Bedroom', '7 Bedroom', '5', '7', '6',
       '5 Bedroom', '11', '9', nan, '9 Bedroom', '27', '10 Bedroom',
       '11 Bedroom', '10', '19', '16', '43 Bedroom', '14', '8',
       '12 Bedroom', '13', '18 Bedroom'], dtype=object)

In [7]:
df["size"]=df["size"].str.replace(" Bedroom","")

In [8]:
df["size"].unique()

array(['2', '4', '3', '6', '1', '1 RK', '8', '7', '5', '11', '9', nan,
       '27', '10', '19', '16', '43', '14', '12', '13', '18'], dtype=object)

In [9]:
df["size"]=df["size"].str.replace(" RK","")

In [10]:
df["size"].unique()

array(['2', '4', '3', '6', '1', '8', '7', '5', '11', '9', nan, '27', '10',
       '19', '16', '43', '14', '12', '13', '18'], dtype=object)

In [11]:
df["size"]=df["size"].fillna("1")

In [12]:
df["size"].unique()

array(['2', '4', '3', '6', '1', '8', '7', '5', '11', '9', '27', '10',
       '19', '16', '43', '14', '12', '13', '18'], dtype=object)

In [13]:
df["size"]=df["size"].astype("int")

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13320 non-null  int64
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 936.7+ KB

In [15]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2,NaN,1200,2.0,1.0,51.00

In [16]:
df["society"].unique()

array(['Coomee ', 'Theanmp', nan, ..., 'SJovest', 'ThhtsV ', 'RSntsAp'],
      dtype=object)

In [17]:
df.isnull().sum()

area_type          0
availability       0
location           1
size               0
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [18]:
df["society"]=df["society"].ffill()

In [19]:
df.isnull().sum()

area_type         0
availability      0
location          1
size              0
society           0
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [20]:
df["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [21]:
df["total_sqft"]

0        1056
1        2600
2        1440
3        1521
4        1200
         ...
13315    3453
13316    3600
13317    1141
13318    4689
13319     550
Name: total_sqft, Length: 13320, dtype: object

In [22]:
def covert_single(x):
    lst=x.split("-")
    if len(lst)==2:
        return (float(lst[0])+float(lst[1]))/2
    try:
        return float(x)
    except:
        return np.nan

In [23]:
df.drop(columns=["sq_feet"],inplace=True)

KeyError: "['sq_feet'] not found in axis"

In [ ]:
df

In [ ]:
df["new_sqft"]=df["total_sqft"].apply(covert_single)

In [ ]:
df

In [ ]:
df["new_sqft"].unique()

In [ ]:
df.isnull().sum()

In [ ]:
df["new_sqft"]=df["new_sqft"].fillna(np.mean(df["new_sqft"]))

In [ ]:
df.isnull().sum()

In [ ]:
df.drop(columns=["total_sqft"],inplace=True)

In [ ]:
df

In [ ]:
df.head(3)

In [ ]:
df["bath"].unique()

In [ ]:
df["bath"]=df["bath"].ffill()

In [ ]:
df["bath"]=df["bath"].astype("int")

In [ ]:
df.info()

In [ ]:
df["balcony"]=df["balcony"].ffill()

In [ ]:
df["balcony"]=df["balcony"].astype("int")

In [ ]:
df.info()

In [ ]:
np.max(df["bath"])

In [ ]:
df=df[df["bath"]<=4]

In [ ]:
df

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

In [ ]:
df1=pd.read_csv("titanic.csv")

In [ ]:
df1

In [ ]:
df1.drop(columns=["PassengerId"],inplace=True)

In [ ]:
df1

In [ ]:
df1.drop(columns=["Name"],inplace=True)

In [ ]:
df1

In [ ]:
df1.isnull().sum()

In [ ]:
df1["Age"]=df1["Age"].fillna(np.median(df1["Age"]))

In [ ]:
df1