In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("diet_recommendation_dataset_1000.csv")

In [3]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet
0,56,0,145,118,56.1,0,131,169,2,Low Carb
1,46,1,166,62,22.5,0,118,253,2,Diabetic
2,32,0,170,83,28.7,1,78,256,2,Diabetic
3,60,1,162,116,44.2,2,161,199,0,Diabetic
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy
...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic
996,43,1,165,52,19.1,2,175,156,2,Diabetic
997,21,0,159,70,27.7,1,126,177,0,Low Carb
998,36,1,171,41,14.0,2,149,249,0,Diabetic
999,37,1,175,55,18.0,1,168,161,1,Diabetic

In [4]:
def creating_categorical(x):
    if x<=30:
        return "young"
    elif x>=31 and x<=45:
        return "adult"
    else:
        return "senior"

In [5]:
df["age_category"]=df["Age"].apply(creating_categorical)

In [6]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet,age_category
0,56,0,145,118,56.1,0,131,169,2,Low Carb,senior
1,46,1,166,62,22.5,0,118,253,2,Diabetic,senior
2,32,0,170,83,28.7,1,78,256,2,Diabetic,adult
3,60,1,162,116,44.2,2,161,199,0,Diabetic,senior
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy,young
...,...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic,young
996,43,1,165,52,19.1,2,175,156,2,Diabetic,adult
997,21,0,159,70,27.7,1,126,177,0,Low Carb,young
998,36,1,171,41,14.0,2,149,249,0,Diabetic,adult
999,37,1,175,55,18.0,1,168,161,1,Diabetic,adult

In [7]:
young=df[df["age_category"]=="young"]["Height_cm"]

In [8]:
young

4      158
9      156
10     151
15     159
17     155
      ...
989    166
990    172
994    146
995    173
997    159
Name: Height_cm, Length: 263, dtype: int64

In [9]:
adult=df[df["age_category"]=="adult"]["Height_cm"]

In [10]:
senior=df[df["age_category"]=="senior"]["Height_cm"]

In [11]:
young_mean=np.mean(young)

In [12]:
adult_mean=np.mean(adult)

In [14]:
senior_mean=np.mean(senior)

In [15]:
overall_mean=np.mean(df["Height_cm"])

In [17]:
young_array=np.array(young)

In [19]:
adult_array=np.array(adult)

In [20]:
senior_array=np.array(senior)

In [21]:
#SSB=summation ni*(xi-bar- x-bar)**2
#SSB=smmaton ni*(group_mean-overall_mean)**2
SSB=(len(young_array)*(young_mean-overall_mean)**2)+(len(adult_array)*(adult_mean-overall_mean)**2)+(len(senior_array)*(senior_mean-overall_mean)**2)

In [22]:
SSB

np.float64(184.96242319400403)

In [27]:
#SSW=summation(x-x-bar)**2
SSW=np.sum((young_array-overall_mean)**2)+np.sum((adult_array-overall_mean)**2)+np.sum((senior_array-overall_mean)**2)

In [28]:
SSW

np.float64(172545.67899999997)

In [44]:
# Df_between=k-1
#Df_within=N-k
Df_between=3-1
Df_within=len(df["Height_cm"])-3

In [45]:
#mean squares
#MSB=SSB/df_between
#MSW=SSW/ Df_within 
#F_statistics=MSB/MSW
MSB=SSB/Df_between

In [46]:
MSW=SSW/ Df_within

In [47]:
F_statistics=MSB/MSW

In [48]:
F_statistics

np.float64(0.5343730917898618)

In [49]:
young_mean

np.float64(167.46768060836501)

In [50]:
adult_mean

np.float64(167.52631578947367)

In [51]:
senior_mean

np.float64(166.6280193236715)

In [52]:
df.columns

Index(['Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI', 'Activity_Level',
       'Sugar_Level', 'Cholesterol', 'Goal', 'Diet', 'age_category'],
      dtype='object')

In [53]:
df["age_category"].value_counts()

age_category
senior    414
adult     323
young     263
Name: count, dtype: int64

In [55]:
df["Diet"].unique()

array(['Low Carb', 'Diabetic', 'Heart Healthy', 'Balanced',
       'High Protein'], dtype=object)

In [56]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet,age_category
0,56,0,145,118,56.1,0,131,169,2,Low Carb,senior
1,46,1,166,62,22.5,0,118,253,2,Diabetic,senior
2,32,0,170,83,28.7,1,78,256,2,Diabetic,adult
3,60,1,162,116,44.2,2,161,199,0,Diabetic,senior
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy,young
...,...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic,young
996,43,1,165,52,19.1,2,175,156,2,Diabetic,adult
997,21,0,159,70,27.7,1,126,177,0,Low Carb,young
998,36,1,171,41,14.0,2,149,249,0,Diabetic,adult
999,37,1,175,55,18.0,1,168,161,1,Diabetic,adult

In [58]:
len(df[df["Sugar_Level"]<=80])

88

In [59]:
len(df[(df["Sugar_Level"]>80) & (df["Sugar_Level"]<=125)])

399

In [62]:
len(df[df["Sugar_Level"]>125])

513

In [63]:
def sugarlevel_cate(x):
    if x<=80:
        return 'Low'
    elif x >= 81 & x<=125:
        return 'Medium'
    else:
        return 'High'

In [64]:
df["sugar_cat"]=df["Sugar_Level"].apply(sugarlevel_cate)

In [65]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet,age_category,sugar_cat
0,56,0,145,118,56.1,0,131,169,2,Low Carb,senior,Medium
1,46,1,166,62,22.5,0,118,253,2,Diabetic,senior,Medium
2,32,0,170,83,28.7,1,78,256,2,Diabetic,adult,Low
3,60,1,162,116,44.2,2,161,199,0,Diabetic,senior,Medium
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy,young,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic,young,Medium
996,43,1,165,52,19.1,2,175,156,2,Diabetic,adult,Medium
997,21,0,159,70,27.7,1,126,177,0,Low Carb,young,Medium
998,36,1,171,41,14.0,2,149,249,0,Diabetic,adult,Medium
999,37,1,175,55,18.0,1,168,161,1,Diabetic,adult,Medium