In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("laptopdata.csv")

In [3]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200
1300,1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200
1301,1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200
1302,1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200

In [5]:
df["Cpu"].unique()

array(['Intel Core i5 2.3GHz', 'Intel Core i5 1.8GHz',
       'Intel Core i5 7200U 2.5GHz', 'Intel Core i7 2.7GHz',
       'Intel Core i5 3.1GHz', 'AMD A9-Series 9420 3GHz',
       'Intel Core i7 2.2GHz', 'Intel Core i7 8550U 1.8GHz',
       'Intel Core i5 8250U 1.6GHz', 'Intel Core i3 6006U 2GHz',
       'Intel Core i7 2.8GHz', 'Intel Core M m3 1.2GHz',
       'Intel Core i7 7500U 2.7GHz', 'Intel Core i7 2.9GHz',
       'Intel Core i3 7100U 2.4GHz', 'Intel Atom x5-Z8350 1.44GHz',
       'Intel Core i5 7300HQ 2.5GHz', 'AMD E-Series E2-9000e 1.5GHz',
       'Intel Core i5 1.6GHz', 'Intel Core i7 8650U 1.9GHz',
       'Intel Atom x5-Z8300 1.44GHz', 'AMD E-Series E2-6110 1.5GHz',
       'AMD A6-Series 9220 2.5GHz',
       'Intel Celeron Dual Core N3350 1.1GHz',
       'Intel Core i3 7130U 2.7GHz', 'Intel Core i7 7700HQ 2.8GHz',
       'Intel Core i5 2.0GHz', 'AMD Ryzen 1700 3GHz',
       'Intel Pentium Quad Core N4200 1.1GHz',
       'Intel Atom x5-Z8550 1.44GHz',
       'Intel Celeron Dual Core N3060 1.6GHz', 'Intel Core i5 1.3GHz',
       'AMD FX 9830P 3GHz', 'Intel Core i7 7560U 2.4GHz',
       'AMD E-Series 6110 1.5GHz', 'Intel Core i5 6200U 2.3GHz',
       'Intel Core M 6Y75 1.2GHz', 'Intel Core i5 7500U 2.7GHz',
       'Intel Core i3 6006U 2.2GHz', 'AMD A6-Series 9220 2.9GHz',
       'Intel Core i7 6920HQ 2.9GHz', 'Intel Core i5 7Y54 1.2GHz',
       'Intel Core i7 7820HK 2.9GHz', 'Intel Xeon E3-1505M V6 3GHz',
       'Intel Core i7 6500U 2.5GHz', 'AMD E-Series 9000e 1.5GHz',
       'AMD A10-Series A10-9620P 2.5GHz', 'AMD A6-Series A6-9220 2.5GHz',
       'Intel Core i5 2.9GHz', 'Intel Core i7 6600U 2.6GHz',
       'Intel Core i3 6006U 2.0GHz',
       'Intel Celeron Dual Core 3205U 1.5GHz',
       'Intel Core i7 7820HQ 2.9GHz', 'AMD A10-Series 9600P 2.4GHz',
       'Intel Core i7 7600U 2.8GHz', 'AMD A8-Series 7410 2.2GHz',
       'Intel Celeron Dual Core 3855U 1.6GHz',
       'Intel Pentium Quad Core N3710 1.6GHz',
       'AMD A12-Series 9720P 2.7GHz', 'Intel Core i5 7300U 2.6GHz',
       'AMD A12-Series 9720P 3.6GHz',
       'Intel Celeron Quad Core N3450 1.1GHz',
       'Intel Celeron Dual Core N3060 1.60GHz',
       'Intel Core i5 6440HQ 2.6GHz', 'Intel Core i7 6820HQ 2.7GHz',
       'AMD Ryzen 1600 3.2GHz', 'Intel Core i7 7Y75 1.3GHz',
       'Intel Core i5 7440HQ 2.8GHz', 'Intel Core i7 7660U 2.5GHz',
       'Intel Core i7 7700HQ 2.7GHz', 'Intel Core M m3-7Y30 2.2GHz',
       'Intel Core i5 7Y57 1.2GHz', 'Intel Core i7 6700HQ 2.6GHz',
       'Intel Core i3 6100U 2.3GHz', 'AMD A10-Series 9620P 2.5GHz',
       'AMD E-Series 7110 1.8GHz', 'Intel Celeron Dual Core N3350 2.0GHz',
       'AMD A9-Series A9-9420 3GHz', 'Intel Core i7 6820HK 2.7GHz',
       'Intel Core M 7Y30 1.0GHz', 'Intel Xeon E3-1535M v6 3.1GHz',
       'Intel Celeron Quad Core N3160 1.6GHz',
       'Intel Core i5 6300U 2.4GHz', 'Intel Core i3 6100U 2.1GHz',
       'AMD E-Series E2-9000 2.2GHz',
       'Intel Celeron Dual Core N3050 1.6GHz',
       'Intel Core M M3-6Y30 0.9GHz', 'AMD A9-Series 9420 2.9GHz',
       'Intel Core i5 6300HQ 2.3GHz', 'AMD A6-Series 7310 2GHz',
       'Intel Atom Z8350 1.92GHz', 'Intel Xeon E3-1535M v5 2.9GHz',
       'Intel Core i5 6260U 1.8GHz',
       'Intel Pentium Dual Core N4200 1.1GHz',
       'Intel Celeron Quad Core N3710 1.6GHz', 'Intel Core M 1.2GHz',
       'AMD A12-Series 9700P 2.5GHz', 'Intel Core i7 7500U 2.5GHz',
       'Intel Pentium Dual Core 4405U 2.1GHz',
       'AMD A4-Series 7210 2.2GHz', 'Intel Core i7 6560U 2.2GHz',
       'Intel Core M m7-6Y75 1.2GHz', 'AMD FX 8800P 2.1GHz',
       'Intel Core M M7-6Y75 1.2GHz', 'Intel Core i5 7200U 2.50GHz',
       'Intel Core i5 7200U 2.70GHz', 'Intel Atom X5-Z8350 1.44GHz',
       'Intel Core i5 7200U 2.7GHz', 'Intel Core M 1.1GHz',
       'Intel Pentium Dual Core 4405Y 1.5GHz',
       'Intel Pentium Quad Core N3700 1.6GHz', 'Intel Core M 6Y54 1.1GHz',
       'Intel Core i7 6500U 2.50GHz',
       'Intel Celeron Dual Core N3350 2GHz',
       'Samsung Cortex A72&A53 2.0GHz', 'AMD E-Series 9000 2.2GHz',
       'Intel Core M 6Y30 0.9GHz', 'AMD A9-Series 9410 2.9GHz'],
      dtype=object)

In [6]:
def conver_cpu(x):
    lst=x.split()
    first_three=lst[0:3]
    return " ".join(first_three)

In [7]:
df["Cpu_name"]=df["Cpu"].apply(conver_cpu)

In [8]:
df.head(3)

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Cpu_name
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel Core i5
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel Core i5
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel Core i5

In [10]:
df["Cpu_name"].value_counts()

Cpu_name
Intel Core i7               527
Intel Core i5               423
Intel Core i3               136
Intel Celeron Dual           80
Intel Pentium Quad           27
Intel Core M                 19
AMD A9-Series 9420           12
AMD A6-Series 9220            8
Intel Celeron Quad            8
AMD A12-Series 9720P          7
Intel Atom x5-Z8350           5
AMD A8-Series 7410            4
Intel Atom x5-Z8550           4
AMD A9-Series 9410            3
Intel Pentium Dual            3
AMD Ryzen 1700                3
AMD A9-Series A9-9420         2
AMD E-Series E2-9000e         2
AMD A10-Series A10-9620P      2
AMD A6-Series A6-9220         2
AMD E-Series 7110             2
AMD A10-Series 9620P          2
AMD A10-Series 9600P          2
Intel Xeon E3-1505M           2
Intel Xeon E3-1535M           2
Intel Atom X5-Z8350           2
Intel Atom x5-Z8300           1
AMD E-Series 6110             1
AMD E-Series 9000e            1
AMD E-Series E2-6110          1
AMD FX 9830P                  1
AMD Ryzen 1600                1
Intel Atom Z8350              1
AMD A6-Series 7310            1
AMD E-Series E2-9000          1
AMD A12-Series 9700P          1
AMD FX 8800P                  1
AMD A4-Series 7210            1
Samsung Cortex A72&A53        1
AMD E-Series 9000             1
Name: count, dtype: int64

In [11]:
df["Cpu_name"].unique()

array(['Intel Core i5', 'Intel Core i7', 'AMD A9-Series 9420',
       'Intel Core i3', 'Intel Core M', 'Intel Atom x5-Z8350',
       'AMD E-Series E2-9000e', 'Intel Atom x5-Z8300',
       'AMD E-Series E2-6110', 'AMD A6-Series 9220', 'Intel Celeron Dual',
       'AMD Ryzen 1700', 'Intel Pentium Quad', 'Intel Atom x5-Z8550',
       'AMD FX 9830P', 'AMD E-Series 6110', 'Intel Xeon E3-1505M',
       'AMD E-Series 9000e', 'AMD A10-Series A10-9620P',
       'AMD A6-Series A6-9220', 'AMD A10-Series 9600P',
       'AMD A8-Series 7410', 'AMD A12-Series 9720P', 'Intel Celeron Quad',
       'AMD Ryzen 1600', 'AMD A10-Series 9620P', 'AMD E-Series 7110',
       'AMD A9-Series A9-9420', 'Intel Xeon E3-1535M',
       'AMD E-Series E2-9000', 'AMD A6-Series 7310', 'Intel Atom Z8350',
       'Intel Pentium Dual', 'AMD A12-Series 9700P', 'AMD A4-Series 7210',
       'AMD FX 8800P', 'Intel Atom X5-Z8350', 'Samsung Cortex A72&A53',
       'AMD E-Series 9000', 'AMD A9-Series 9410'], dtype=object)

In [13]:
def convert_to_word(x):
    if "Intel" in x:
        return "Intel"
    elif "AMD" in x:
        return "AMD"
    else:
        return "Other"

In [14]:
df["Cpu_cat"]=df["Cpu_name"].apply(convert_to_word)

In [15]:
df.head(3)

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price,Cpu_name,Cpu_cat
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel Core i5,Intel
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel Core i5,Intel
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel Core i5,Intel

In [16]:
df["Cpu_cat"].unique()

array(['Intel', 'AMD', 'Other'], dtype=object)

In [17]:
df.drop(columns=["Cpu","Cpu_name"],inplace=True)

In [18]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,Memory,Gpu,OpSys,Weight,Price,Cpu_cat
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel
1,1,Apple,Ultrabook,13.3,1440x900,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360,Intel
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080,Intel
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400,Intel
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200,Intel
1300,1300,Lenovo,Notebook,14.0,1366x768,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200,Intel
1301,1301,HP,Notebook,15.6,1366x768,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200,Intel
1302,1302,Asus,Notebook,15.6,1366x768,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200,Intel

In [19]:
df["Memory"]

0                 128GB SSD
1       128GB Flash Storage
2                 256GB SSD
3                 512GB SSD
4                 256GB SSD
               ...
1298              128GB SSD
1299              512GB SSD
1300     64GB Flash Storage
1301                1TB HDD
1302              500GB HDD
Name: Memory, Length: 1303, dtype: object

In [20]:
df["Memory"].value_counts()

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
1TB SSD                           14
512GB SSD +  1TB HDD              14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
16GB SSD                           3
512GB SSD +  2TB HDD               3
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
64GB SSD                           1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
512GB SSD +  256GB SSD             1
32GB HDD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [21]:
df["Memory"]=df["Memory"].str.replace(".0","")

In [22]:
df["Memory"].value_counts()

Memory
256GB SSD                        412
1TB HDD                          224
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1TB Hybrid                         9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
256GB SSD +  256GB SSD             2
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
512GB SSD +  512GB SSD             1
64GB SSD                           1
512GB SSD +  256GB SSD             1
64GB Flash Storage +  1TB HDD      1
32GB HDD                           1
1TB HDD +  1TB HDD                 1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
512GB SSD +  1TB Hybrid            1
256GB SSD +  1TB Hybrid            1
Name: count, dtype: int64

In [23]:
df["Memory"]=df["Memory"].str.replace("GB","")
df["Memory"]=df["Memory"].str.replace("TB","000")

In [24]:
df["Memory"].value_counts()

Memory
256 SSD                         412
1000 HDD                        224
500 HDD                         132
512 SSD                         118
128 SSD +  1000 HDD              94
128 SSD                          76
256 SSD +  1000 HDD              73
32 Flash Storage                 38
2000 HDD                         16
64 Flash Storage                 15
512 SSD +  1000 HDD              14
1000 SSD                         14
256 SSD +  2000 HDD              10
1000 Hybrid                       9
256 Flash Storage                 8
16 Flash Storage                  7
32 SSD                            6
180 SSD                           5
128 Flash Storage                 4
512 SSD +  2000 HDD               3
16 SSD                            3
256 SSD +  256 SSD                2
512 Flash Storage                 2
1000 SSD +  1000 HDD              2
256 SSD +  500 HDD                2
128 SSD +  2000 HDD               2
512 SSD +  512 SSD                1
64 SSD                            1
512 SSD +  256 SSD                1
64 Flash Storage +  1000 HDD      1
32 HDD                            1
1000 HDD +  1000 HDD              1
128 HDD                           1
240 SSD                           1
8 SSD                             1
508 Hybrid                        1
512 SSD +  1000 Hybrid            1
256 SSD +  1000 Hybrid            1
Name: count, dtype: int64

In [25]:
new=df["Memory"].str.split("+",n=1,expand=True)

In [26]:
new

                      0     1
0               128 SSD  None
1     128 Flash Storage  None
2               256 SSD  None
3               512 SSD  None
4               256 SSD  None
...                 ...   ...
1298            128 SSD  None
1299            512 SSD  None
1300   64 Flash Storage  None
1301           1000 HDD  None
1302            500 HDD  None

[1303 rows x 2 columns]

In [27]:
new[0]

0                 128 SSD
1       128 Flash Storage
2                 256 SSD
3                 512 SSD
4                 256 SSD
              ...
1298              128 SSD
1299              512 SSD
1300     64 Flash Storage
1301             1000 HDD
1302              500 HDD
Name: 0, Length: 1303, dtype: object

In [28]:
new[1].unique()

array([None, '  1000 HDD', '  256 SSD', '  2000 HDD', '  500 HDD',
       '  512 SSD', '  1000 Hybrid'], dtype=object)

In [29]:
df["tp1"]=new[0]
df["tp2"]=new[1]

In [30]:
df["HDD1"]=df["tp1"].apply(lambda x:1 if "HDD" in x else 0)
df["SSD1"]=df["tp1"].apply(lambda x:1 if "SSD" in x else 0)
df["Hybrid1"]=df["tp1"].apply(lambda x:1 if "Hybrid" in x else 0)
df["Flash1"]=df["tp1"].apply(lambda x:1 if "Flash Storage" in x else 0)

In [32]:
df["tp2"].fillna("0",inplace=True)

In [33]:
df["HDD2"]=df["tp2"].apply(lambda x:1 if "HDD" in x else 0)
df["SSD2"]=df["tp2"].apply(lambda x:1 if "SSD" in x else 0)
df["Hybrid2"]=df["tp2"].apply(lambda x:1 if "Hybrid" in x else 0)
df["Flash2"]=df["tp2"].apply(lambda x:1 if "Flash Storage" in x else 0)

In [34]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,Memory,Gpu,OpSys,Weight,...,tp1,tp2,HDD1,SSD1,Hybrid1,Flash1,HDD2,SSD2,Hybrid2,Flash2
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,128 SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,...,128 SSD,0,0,1,0,0,0,0,0,0
1,1,Apple,Ultrabook,13.3,1440x900,8GB,128 Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,...,128 Flash Storage,0,0,0,0,1,0,0,0,0
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,256 SSD,Intel HD Graphics 620,No OS,1.86kg,...,256 SSD,0,0,1,0,0,0,0,0,0
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16GB,512 SSD,AMD Radeon Pro 455,macOS,1.83kg,...,512 SSD,0,0,1,0,0,0,0,0,0
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,256 SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,...,256 SSD,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4GB,128 SSD,Intel HD Graphics 520,Windows 10,1.8kg,...,128 SSD,0,0,1,0,0,0,0,0,0
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16GB,512 SSD,Intel HD Graphics 520,Windows 10,1.3kg,...,512 SSD,0,0,1,0,0,0,0,0,0
1300,1300,Lenovo,Notebook,14.0,1366x768,2GB,64 Flash Storage,Intel HD Graphics,Windows 10,1.5kg,...,64 Flash Storage,0,0,0,0,1,0,0,0,0
1301,1301,HP,Notebook,15.6,1366x768,6GB,1000 HDD,AMD Radeon R5 M330,Windows 10,2.19kg,...,1000 HDD,0,1,0,0,0,0,0,0,0
1302,1302,Asus,Notebook,15.6,1366x768,4GB,500 HDD,Intel HD Graphics,Windows 10,2.2kg,...,500 HDD,0,1,0,0,0,0,0,0,0

In [35]:
df["tp1"]

0                 128 SSD
1       128 Flash Storage
2                 256 SSD
3                 512 SSD
4                 256 SSD
              ...
1298              128 SSD
1299              512 SSD
1300     64 Flash Storage
1301             1000 HDD
1302              500 HDD
Name: tp1, Length: 1303, dtype: object

In [36]:
df["tp2"]

0       0
1       0
2       0
3       0
4       0
       ..
1298    0
1299    0
1300    0
1301    0
1302    0
Name: tp2, Length: 1303, dtype: object

In [37]:
df["tp1"]=df["tp1"].str.replace("\D","",regex=True)

In [38]:
df["tp1"]

0        128
1        128
2        256
3        512
4        256
        ...
1298     128
1299     512
1300      64
1301    1000
1302     500
Name: tp1, Length: 1303, dtype: object

In [39]:
df["tp2"]=df["tp2"].str.replace("\D","",regex=True)

In [40]:
df["tp2"]

0       0
1       0
2       0
3       0
4       0
       ..
1298    0
1299    0
1300    0
1301    0
1302    0
Name: tp2, Length: 1303, dtype: object

In [41]:
df["tp1"]=df["tp1"].astype("int")
df["tp2"]=df["tp2"].astype("int")

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   int64
 1   Company           1303 non-null   object
 2   TypeName          1303 non-null   object
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   object
 5   Ram               1303 non-null   object
 6   Memory            1303 non-null   object
 7   Gpu               1303 non-null   object
 8   OpSys             1303 non-null   object
 9   Weight            1303 non-null   object
 10  Price             1303 non-null   float64
 11  Cpu_cat           1303 non-null   object
 12  tp1               1303 non-null   int64
 13  tp2               1303 non-null   int64
 14  HDD1              1303 non-null   int64
 15  SSD1              1303 non-null   int64
 16  Hybrid1           1303 non-null   int64
 17  Flash1            1303 non-null   int64
 18  HDD2              1303 non-null   int64
 19  SSD2              1303 non-null   int64
 20  Hybrid2           1303 non-null   int64
 21  Flash2            1303 non-null   int64
dtypes: float64(2), int64(11), object(9)
memory usage: 224.1+ KB

In [43]:
df["HDD"]=((df["HDD1"]*df["tp1"])+(df["HDD2"]*df["tp2"]))
df["SSD"]=((df["SSD1"]*df["tp1"])+(df["SSD2"]*df["tp2"]))
df["Hybrid"]=((df["Hybrid1"]*df["tp1"])+(df["Hybrid2"]*df["tp2"]))
df["Flash"]=((df["Flash1"]*df["tp1"])+(df["Flash2"]*df["tp2"]))

In [44]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,Memory,Gpu,OpSys,Weight,...,Hybrid1,Flash1,HDD2,SSD2,Hybrid2,Flash2,HDD,SSD,Hybrid,Flash
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,128 SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,...,0,0,0,0,0,0,0,128,0,0
1,1,Apple,Ultrabook,13.3,1440x900,8GB,128 Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,...,0,1,0,0,0,0,0,0,0,128
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,256 SSD,Intel HD Graphics 620,No OS,1.86kg,...,0,0,0,0,0,0,0,256,0,0
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16GB,512 SSD,AMD Radeon Pro 455,macOS,1.83kg,...,0,0,0,0,0,0,0,512,0,0
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,256 SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,...,0,0,0,0,0,0,0,256,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4GB,128 SSD,Intel HD Graphics 520,Windows 10,1.8kg,...,0,0,0,0,0,0,0,128,0,0
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16GB,512 SSD,Intel HD Graphics 520,Windows 10,1.3kg,...,0,0,0,0,0,0,0,512,0,0
1300,1300,Lenovo,Notebook,14.0,1366x768,2GB,64 Flash Storage,Intel HD Graphics,Windows 10,1.5kg,...,0,1,0,0,0,0,0,0,0,64
1301,1301,HP,Notebook,15.6,1366x768,6GB,1000 HDD,AMD Radeon R5 M330,Windows 10,2.19kg,...,0,0,0,0,0,0,1000,0,0,0
1302,1302,Asus,Notebook,15.6,1366x768,4GB,500 HDD,Intel HD Graphics,Windows 10,2.2kg,...,0,0,0,0,0,0,500,0,0,0

In [45]:
df.drop(columns=["tp1","tp2","HDD1","HDD2","SSD1","SSD2","Hybrid1","Hybrid2","Flash1","Flash2"],inplace=True)

In [46]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,Memory,Gpu,OpSys,Weight,Price,Cpu_cat,HDD,SSD,Hybrid,Flash
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,128 SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel,0,128,0,0
1,1,Apple,Ultrabook,13.3,1440x900,8GB,128 Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel,0,0,0,128
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,256 SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel,0,256,0,0
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16GB,512 SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360,Intel,0,512,0,0
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,256 SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080,Intel,0,256,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4GB,128 SSD,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400,Intel,0,128,0,0
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16GB,512 SSD,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200,Intel,0,512,0,0
1300,1300,Lenovo,Notebook,14.0,1366x768,2GB,64 Flash Storage,Intel HD Graphics,Windows 10,1.5kg,12201.1200,Intel,0,0,0,64
1301,1301,HP,Notebook,15.6,1366x768,6GB,1000 HDD,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200,Intel,1000,0,0,0
1302,1302,Asus,Notebook,15.6,1366x768,4GB,500 HDD,Intel HD Graphics,Windows 10,2.2kg,19660.3200,Intel,500,0,0,0

In [47]:
df.drop(columns=["Memory"],inplace=True)

In [48]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,Gpu,OpSys,Weight,Price,Cpu_cat,HDD,SSD,Hybrid,Flash
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel,0,128,0,0
1,1,Apple,Ultrabook,13.3,1440x900,8GB,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel,0,0,0,128
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel,0,256,0,0
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16GB,AMD Radeon Pro 455,macOS,1.83kg,135195.3360,Intel,0,512,0,0
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080,Intel,0,256,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4GB,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400,Intel,0,128,0,0
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16GB,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200,Intel,0,512,0,0
1300,1300,Lenovo,Notebook,14.0,1366x768,2GB,Intel HD Graphics,Windows 10,1.5kg,12201.1200,Intel,0,0,0,64
1301,1301,HP,Notebook,15.6,1366x768,6GB,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200,Intel,1000,0,0,0
1302,1302,Asus,Notebook,15.6,1366x768,4GB,Intel HD Graphics,Windows 10,2.2kg,19660.3200,Intel,500,0,0,0

In [49]:
df.head(3)

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,Gpu,OpSys,Weight,Price,Cpu_cat,HDD,SSD,Hybrid,Flash
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel,0,128,0,0
1,1,Apple,Ultrabook,13.3,1440x900,8GB,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel,0,0,0,128
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel,0,256,0,0

In [50]:
df["Gpu"]

0       Intel Iris Plus Graphics 640
1             Intel HD Graphics 6000
2              Intel HD Graphics 620
3                 AMD Radeon Pro 455
4       Intel Iris Plus Graphics 650
                    ...
1298           Intel HD Graphics 520
1299           Intel HD Graphics 520
1300               Intel HD Graphics
1301              AMD Radeon R5 M330
1302               Intel HD Graphics
Name: Gpu, Length: 1303, dtype: object

In [51]:
def convert_gpu(x):
    words=x.split()
    first_three=words[0:3]
    return " ".join(first_three)

In [52]:
df["Gpu_name"]=df["Gpu"].apply(convert_gpu)

In [53]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,Gpu,OpSys,Weight,Price,Cpu_cat,HDD,SSD,Hybrid,Flash,Gpu_name
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel,0,128,0,0,Intel Iris Plus
1,1,Apple,Ultrabook,13.3,1440x900,8GB,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel,0,0,0,128,Intel HD Graphics
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel,0,256,0,0,Intel HD Graphics
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16GB,AMD Radeon Pro 455,macOS,1.83kg,135195.3360,Intel,0,512,0,0,AMD Radeon Pro
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080,Intel,0,256,0,0,Intel Iris Plus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4GB,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400,Intel,0,128,0,0,Intel HD Graphics
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16GB,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200,Intel,0,512,0,0,Intel HD Graphics
1300,1300,Lenovo,Notebook,14.0,1366x768,2GB,Intel HD Graphics,Windows 10,1.5kg,12201.1200,Intel,0,0,0,64,Intel HD Graphics
1301,1301,HP,Notebook,15.6,1366x768,6GB,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200,Intel,1000,0,0,0,AMD Radeon R5
1302,1302,Asus,Notebook,15.6,1366x768,4GB,Intel HD Graphics,Windows 10,2.2kg,19660.3200,Intel,500,0,0,0,Intel HD Graphics

In [54]:
df["Gpu_name"].unique()

array(['Intel Iris Plus', 'Intel HD Graphics', 'AMD Radeon Pro',
       'AMD Radeon R5', 'Intel Iris Pro', 'Nvidia GeForce MX150',
       'Intel UHD Graphics', 'Nvidia GeForce 940MX', 'Nvidia GeForce GTX',
       'AMD Radeon R2', 'AMD Radeon 530', 'Nvidia GeForce 930MX',
       'Nvidia GeForce 150MX', 'Intel Iris Graphics', 'AMD Radeon RX',
       'Nvidia GeForce 920MX', 'AMD Radeon R4', 'AMD Radeon 520',
       'Nvidia GeForce MX130', 'AMD R4 Graphics', 'Nvidia GeForce 920M',
       'AMD Radeon R7', 'Nvidia GTX 980', 'AMD R17M-M1-70',
       'Nvidia Quadro M1200', 'AMD FirePro W4190M', 'Nvidia GeForce 930M',
       'Nvidia GeForce GT', 'AMD FirePro W5130M', 'Nvidia Quadro M2200M',
       'Nvidia Quadro M620', 'Nvidia GeForce GTX1080',
       'Nvidia GeForce GTX1050', 'Nvidia Quadro M620M',
       'Intel Graphics 620', 'Nvidia Quadro M520M', 'Nvidia Quadro M2200',
       'Nvidia Quadro M2000M', 'Nvidia Quadro M1000M', 'AMD Radeon 540',
       'Nvidia GeForce GTX1060', 'Nvidia GeForce 920',
       'Nvidia GeForce 940M', 'AMD Radeon R3', 'AMD Radeon R9',
       'Nvidia Quadro 3000M', 'AMD FirePro W6150M', 'Nvidia Quadro M500M',
       'Nvidia Quadro M3000M', 'Nvidia GeForce 960M', 'ARM Mali T860'],
      dtype=object)

In [55]:
def gpu_category(x):
    if "Intel" in x:
        return "Intel"
    elif "Nvidia" in x:
        return "Nvidia"
    elif "AMD" in x:
        return "AMD"
    else:
        return "other"

In [56]:
df["Gpu_cat"]=df["Gpu_name"].apply(gpu_category)

In [57]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,Gpu,OpSys,Weight,Price,Cpu_cat,HDD,SSD,Hybrid,Flash,Gpu_name,Gpu_cat
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832,Intel,0,128,0,0,Intel Iris Plus,Intel
1,1,Apple,Ultrabook,13.3,1440x900,8GB,Intel HD Graphics 6000,macOS,1.34kg,47895.5232,Intel,0,0,0,128,Intel HD Graphics,Intel
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,Intel HD Graphics 620,No OS,1.86kg,30636.0000,Intel,0,256,0,0,Intel HD Graphics,Intel
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16GB,AMD Radeon Pro 455,macOS,1.83kg,135195.3360,Intel,0,512,0,0,AMD Radeon Pro,AMD
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080,Intel,0,256,0,0,Intel Iris Plus,Intel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4GB,Intel HD Graphics 520,Windows 10,1.8kg,33992.6400,Intel,0,128,0,0,Intel HD Graphics,Intel
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16GB,Intel HD Graphics 520,Windows 10,1.3kg,79866.7200,Intel,0,512,0,0,Intel HD Graphics,Intel
1300,1300,Lenovo,Notebook,14.0,1366x768,2GB,Intel HD Graphics,Windows 10,1.5kg,12201.1200,Intel,0,0,0,64,Intel HD Graphics,Intel
1301,1301,HP,Notebook,15.6,1366x768,6GB,AMD Radeon R5 M330,Windows 10,2.19kg,40705.9200,Intel,1000,0,0,0,AMD Radeon R5,AMD
1302,1302,Asus,Notebook,15.6,1366x768,4GB,Intel HD Graphics,Windows 10,2.2kg,19660.3200,Intel,500,0,0,0,Intel HD Graphics,Intel

In [58]:
df.drop(columns=["Gpu","Gpu_name"],inplace=True)

In [59]:
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Ram,OpSys,Weight,Price,Cpu_cat,HDD,SSD,Hybrid,Flash,Gpu_cat
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,macOS,1.37kg,71378.6832,Intel,0,128,0,0,Intel
1,1,Apple,Ultrabook,13.3,1440x900,8GB,macOS,1.34kg,47895.5232,Intel,0,0,0,128,Intel
2,2,HP,Notebook,15.6,Full HD 1920x1080,8GB,No OS,1.86kg,30636.0000,Intel,0,256,0,0,Intel
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,16GB,macOS,1.83kg,135195.3360,Intel,0,512,0,0,AMD
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,8GB,macOS,1.37kg,96095.8080,Intel,0,256,0,0,Intel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,4GB,Windows 10,1.8kg,33992.6400,Intel,0,128,0,0,Intel
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,16GB,Windows 10,1.3kg,79866.7200,Intel,0,512,0,0,Intel
1300,1300,Lenovo,Notebook,14.0,1366x768,2GB,Windows 10,1.5kg,12201.1200,Intel,0,0,0,64,Intel
1301,1301,HP,Notebook,15.6,1366x768,6GB,Windows 10,2.19kg,40705.9200,Intel,1000,0,0,0,AMD
1302,1302,Asus,Notebook,15.6,1366x768,4GB,Windows 10,2.2kg,19660.3200,Intel,500,0,0,0,Intel